application: sreeramvuppala
version: 3
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css|doc))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|doc))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
